### ISSUE TITLE
Does not work with f.lux

### ISSUE THREAD

**Issue by plyght** [niklasr22/BrightIntosh#104]
Every time i use brightintosh, i need to quit [f.lux](https://justgetflux.com). is there a way to fix?

**Comment by niklasr22** [comment]
My guess is that f.lux (I couldn't find its source code) and BrightIntosh use the same MacOS APIs to change the appearance of the screen, so that they overwrite each other's settings.
I'm not sure if this is a problem that BrightIntosh can fix.
One possibility might be to periodically check if the settings have been changed by another application and reset them to BrightIntosh's settings, but this might cause strange flickering.

**Comment by plyght** [comment]
i'm not sure if this'll help, but here's the linux f.lux source code: [https://github.com/xflux-gui/fluxgui](f.lux linux source code)

**Comment by niklasr22** [comment]
Because Linux and MacOS have different APIs, I don't think there's much information to be gathered.
I'm afraid we have to accept that these two applications will not work at the same time.

Of course you can still try to find a solution yourself and feel free to open a pull request.
